title: "ACTRESS Toolkit"
description: "Documentation for the ACTRESS Toolkit"

pygments: true

docs:
  - 
    title: Feedbck Control Description Model (FCDM) 
    url: fcdm.html
    desc: The ACTRESS meta-model for describing feedback control.
  - 
    title: Feedback Control Description Language (FCDL)
    url: fcdl.html
    desc: The ACTRESS DSL for creating the FCDM models. 
