title: "The ACTRESS Modeling Environment"
description: "Documentation for the ACTRESS Modeling Environment"

pygments: true

docs:
  - 
    title: Feedback Control Definition Language (FCDL)
    url: FCDL.pdf
    desc: Technical report documenting the domain-specific modeling language for defining self-adaptive software system architectures through external feedback control loops and the ACTRESS modeling environment. 
